#!/usr/bin/env python3
"""Inspect an inline SVG chart the way a browser would — parse it, draw it, look.

Presence is not correctness. Post 1590 shipped an <svg> that the old gate waved
through ("[PASS] chart present") and that rendered as an empty cream box, because
one closing tag read </title> where it should have read </text>. A second chart
in the same post had its '780000' value label clipped off the right edge of the
card. Neither is detectable by asking "is there an <svg> in the content?".

Three checks, cheapest first:

  1. well-formed   — XML parse. The </title> class, exactly.
  2. renderable    — cairosvg actually rasterizes it. Catches duplicate
                     attributes and other things expat tolerates but renderers
                     do not.
  3. inside-frame  — re-render with the viewBox widened by a margin on all four
                     sides. Anything that draws into that margin would have been
                     clipped at the real viewBox. This is measured in pixels
                     from a real text shaper, not estimated from character
                     counts — an estimate was tried first and produced a third
                     false-positive rate, which is worse than no check.

Font note: the frontend loads Lora / IBM Plex Sans; cairo has neither and falls
back to DejaVu Sans, which is wider. That makes check 3 conservative — a chart
that fits here fits in the browser. Charts generated by build_chart.py reserve
24px of right pad, well clear of the substitution error.

If cairosvg is unavailable, checks 2-3 are skipped and reported as skipped
rather than passed — a missing renderer must not look like a clean bill.
"""

import io
import re
import xml.etree.ElementTree as ET

SVG_RE = re.compile(r"<svg\b[^>]*>.*?</svg>", re.DOTALL | re.IGNORECASE)

# Widened-frame margin, px. Wide enough that a badly overflowing label lands
# inside it rather than off the rendered canvas entirely.
MARGIN = 48

# Ignore ink smaller than this in either dimension — antialiasing fringe on the
# card's rounded corners can tint the odd boundary pixel.
MIN_INK = 2

# Minimum viewBox width for an <svg> to be treated as a chart. Article bodies
# also carry decorative SVG that is nobody's chart — WordPress plugin icons, for
# instance: post 769 embeds 24x24 table sort-arrows that fail an XML parse on a
# duplicate attribute. Inspecting those would block a publish over an icon. Our
# charts are 560 wide; icons are 16-32. Anything without a readable viewBox is
# still inspected, so a malformed chart can't hide by losing its viewBox.
MIN_CHART_WIDTH = 200

VIEWBOX_RE = re.compile(
    r'viewBox="([-\d.]+)\s+([-\d.]+)\s+([\d.]+)\s+([\d.]+)"', re.IGNORECASE
)

try:
    import cairosvg
    from PIL import Image
    _CAN_RENDER = True
except ImportError:  # pragma: no cover - depends on host env
    _CAN_RENDER = False


def find_svgs(html: str) -> list[str]:
    """Every inline <svg>...</svg> in a chunk of HTML, in document order."""
    return SVG_RE.findall(html)


def is_chart(svg: str) -> bool:
    """True unless this <svg> is clearly a decorative icon rather than a chart."""
    m = VIEWBOX_RE.search(svg)
    if not m:
        return True  # can't tell — inspect it rather than wave it through
    try:
        return float(m.group(3)) >= MIN_CHART_WIDTH
    except ValueError:
        return True


def find_charts(html: str) -> list[str]:
    """Inline SVGs that are actually charts — icons filtered out."""
    return [s for s in find_svgs(html) if is_chart(s)]


def _widen(svg: str) -> tuple[str, float, float] | None:
    """Return the SVG with its viewBox grown by MARGIN on every side.

    Attribute matching is case-insensitive on purpose: WordPress stores the
    markup normalized — attributes alphabetized and `viewBox` folded to
    `viewbox`. Browsers case-correct that back per the HTML spec's foreign-content
    adjustment table, so it renders fine and we must read it the same way. A
    case-sensitive match here reported "no parseable viewBox" on every live post.
    """
    # cairosvg honours the max-width style and renders a blank surface; drop it.
    s = re.sub(r'\sstyle="[^"]*max-width[^"]*"', "", svg, count=1, flags=re.IGNORECASE)
    m = re.search(r'viewBox="([-\d.]+)\s+([-\d.]+)\s+([\d.]+)\s+([\d.]+)"', s, re.IGNORECASE)
    if not m:
        return None
    x0, y0, w, h = (float(g) for g in m.groups())
    new_vb = f'viewBox="{x0 - MARGIN} {y0 - MARGIN} {w + 2 * MARGIN} {h + 2 * MARGIN}"'
    s = s[: m.start()] + new_vb + s[m.end():]
    s = re.sub(r"<svg\b", f'<svg width="{w + 2 * MARGIN:.0f}" height="{h + 2 * MARGIN:.0f}"', s, count=1)
    return s, w, h


# <text> may legitimately contain these; anything else nested inside it means an
# unclosed tag swallowed the rest of the graphic.
_TEXT_CHILDREN_OK = {"tspan", "textPath", "a", "title", "desc"}


def _swallowed(root) -> list[str]:
    """Drawable elements nested inside <text>/<title> — the unclosed-tag signature.

    Post 1590's chart closed a <text> with </title>. BeautifulSoup 'repaired' that
    on upload by leaving the <text> open and nesting every following element inside
    it, which is well-formed XML and renders as an empty card: content inside <text>
    doesn't draw. So neither an XML parse nor a rasterize catches it on live content
    — only the structure does.
    """
    problems = []
    for parent in root.iter():
        if parent.tag.split("}")[-1] not in ("text", "title"):
            continue
        strays = [c.tag.split("}")[-1] for c in parent
                  if c.tag.split("}")[-1] not in _TEXT_CHILDREN_OK]
        if strays:
            label = (parent.text or "").strip()[:40]
            problems.append(
                f"<{parent.tag.split('}')[-1]}>{label!r} contains nested "
                f"{', '.join(sorted(set(strays)))} — an unclosed tag swallowed the graphic"
            )
    return problems


def inspect_svg(svg: str) -> list[str]:
    """Return a list of human-readable problems. Empty list means the chart is fine."""
    try:
        root = ET.fromstring(svg)
    except ET.ParseError as exc:
        return [f"malformed SVG — {exc}"]

    swallowed = _swallowed(root)
    if swallowed:
        return swallowed

    if not _CAN_RENDER:
        return []

    widened = _widen(svg)
    if widened is None:
        return ["no parseable viewBox"]
    wide_svg, _w, _h = widened

    try:
        png = cairosvg.svg2png(bytestring=wide_svg.encode("utf-8"))
    except Exception as exc:  # noqa: BLE001 - any renderer failure is a real defect
        return [f"does not render — {type(exc).__name__}: {str(exc)[:90]}"]

    alpha = Image.open(io.BytesIO(png)).convert("RGBA").split()[3]
    width, height = alpha.size
    regions = {
        "left": (0, 0, MARGIN, height),
        "right": (width - MARGIN, 0, width, height),
        "top": (0, 0, width, MARGIN),
        "bottom": (0, height - MARGIN, width, height),
    }

    spills = []
    for side, box in regions.items():
        bbox = alpha.crop(box).getbbox()
        if not bbox:
            continue
        ink_w, ink_h = bbox[2] - bbox[0], bbox[3] - bbox[1]
        if ink_w < MIN_INK or ink_h < MIN_INK:
            continue
        over = ink_w if side in ("left", "right") else ink_h
        spills.append(f"{over}px past the {side} edge")

    return [f"content clipped: {', '.join(spills)}"] if spills else []


def inspect_html(html: str) -> list[str]:
    """Inspect every chart in an HTML document. Returns problems, chart-numbered.

    Decorative icons are skipped — see MIN_CHART_WIDTH. This is the live-content
    path; render_charts.py inspects freshly built charts directly and applies no
    such filter.
    """
    problems = []
    for i, svg in enumerate(find_charts(html), 1):
        problems.extend(f"chart {i}: {p}" for p in inspect_svg(svg))
    return problems


def renderer_available() -> bool:
    return _CAN_RENDER
